spring:
  # MySQL 데이터베이스 설정
  datasource:
    # SQL 쿼리에서 'localhost'를 사용했으므로, 여기도 'localhost'를 사용합니다.
    url: jdbc:mysql://localhost:3306/login?useSSL=false&serverTimezone=Asia/Seoul
    # MySQL Workbench에서 만든 사용자 이름과 동일해야 합니다.
    username: uni4
    # MySQL Workbench에서 만든 비밀번호와 동일해야 합니다.
    password: uni41234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Spring Security OAuth2 클라이언트 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 339251245515-huhlklc77maqfr9mq2aie131td07l308.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          kakao:
            client-id: f2c55a4afe421cc4192bc10d6f452b4b
            #            client-secret: YOUR_KAKAO_CLIENT_SECRET
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: 750d33983a05349a46c6f17b43ef5fc6aac28bec305302780107a7379f67d3db